### ISSUE TITLE
Python Binding在windows下无法编译

### ISSUE THREAD

**Issue by AppleJunJiang** [QwenLM/qwen.cpp#37]
FileTracker : error FTK1011: 未能创建新的文件跟踪日志文件: C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\strings\str_format_internal.dir\Release\str_form.7DC54622.tlog\Lib-link.write.1.tlog。系统找不到指定的路径。 [C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\strings\str_format_internal.vcxproj]

        time.vcxproj -> C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\lib\Release\absl_time.lib
      D:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: 中间目录或输出目录无法驻留在临时目录下，因为这可能会导致增量生成出现问题。 [C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\synchronization\kernel_timeout_internal.vcxproj]
        Building Custom Rule C:/Users/APPLE/AppData/Local/Temp/pip-install-airc0i7k/qwen-cpp_8ded2d7eb7fd4067b8a5507093082779/third_party/abseil-cpp/absl/synchronization/CMakeLists.txt
      cl : 命令行  warning D9002: 忽略未知选项“-g” [C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\synchronization\kernel_timeout_internal.vcxproj]
        kernel_timeout.cc
      FileTracker : error FTK1011: 未能创建新的文件跟踪日志文件: C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\synchronization\kernel_timeout_internal.dir\Release\kernel_t.08734163.tlog\Lib-link.read.1.tlog。系统找不到指定的路径 。 [C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\synchronization\kernel_timeout_internal.vcxproj]

      FileTracker : error FTK1011: 未能创建新的文件跟踪日志文件: C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\synchronization\kernel_timeout_internal.dir\Release\kernel_t.08734163.tlog\Lib-link.write.1.tlog。系统找不到指定的路径。 [C:\Users\APPLE\AppData\Local\Temp\pip-install-airc0i7k\qwen-cpp_8ded2d7eb7fd4067b8a5507093082779\build\temp.win-amd64-cpython-39\Release\qwen_cpp._C\third_party\abseil-cpp\absl\synchronization\kernel_timeout_internal.vcxproj]

      Traceback (most recent call last):
        File "C:\Users\APPLE\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\APPLE\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\APPLE\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 116, in <module>
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\normal\Lib\site-packages\wheel\bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\APPLE\AppData\Local\Temp\pip-build-env-xkbp0t3f\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 111, in build_extension
        File "C:\Users\APPLE\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '-j']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qwen-cpp
Failed to build qwen-cpp
ERROR: Could not build wheels for qwen-cpp, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.

**Comment by linchuanz2000** [comment]
readme里说只支持mac和linux，，，
