### ISSUE TITLE
pip install -U qwen-cpp 报错

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/qwen.cpp#58]
[ 98%] Built target flags_parse
      [ 99%] Linking CXX static library lib/libqwen.a
      [ 99%] Built target qwen
      [ 99%] Building CXX object CMakeFiles/main.dir/main.cpp.o
      [ 99%] Building CXX object CMakeFiles/_C.dir/qwen_pybind.cpp.o
      In file included from /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/qwen.h:3,
                       from /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/main.cpp:1:
      /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/tiktoken.h: In lambda function:
      /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/tiktoken.h:33:28: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<int, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         33 |   if (start_idx + skip + 2 < parts.size()) {
            |       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      In file included from /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/qwen_pybind.cpp:1:
      /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/tiktoken.h: In lambda function:
      /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/tiktoken.h:33:28: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<int, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         33 |   if (start_idx + skip + 2 < parts.size()) {
            |       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      [100%] Linking CXX executable bin/main
      [100%] Built target main
      [100%] Linking CXX shared module /tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/build/lib.linux-x86_64-cpython-310/qwen_cpp/_C.cpython-310-x86_64-linux-gnu.so
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(re2.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(regexp.cc.o): relocation R_X86_64_32S against symbol `_ZN4absl18container_internal11kEmptyGroupE' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(strutil.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(bitstate.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(compile.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(dfa.cc.o): relocation R_X86_64_32 against symbol `_ZZN4absl18container_internal12raw_hash_setINS0_17FlatHashSetPolicyIPN3re23DFA5StateEEENS4_9StateHashENS4_10StateEqualESaIS6_EE18GetPolicyFunctionsEvE5value' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(nfa.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(onepass.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(parse.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(prog.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(simplify.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(tostring.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_raw_hash_set.a(raw_hash_set.cc.o): relocation R_X86_64_TPOFF32 against `_ZZN4absl18container_internal12_GLOBAL__N_110RandomSeedEvE7counter' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_hash.a(hash.cc.o): relocation R_X86_64_32 against symbol `_ZN4absl13hash_internal15MixingHashState5kSeedE' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_str_format_internal.a(arg.cc.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_str_format_internal.a(bind.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_str_format_internal.a(extension.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_str_format_internal.a(float_conversion.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_str_format_internal.a(output.cc.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_str_format_internal.a(parser.cc.o): relocation R_X86_64_32S against symbol `_ZN4absl19str_format_internal13ConvTagHolder5valueE' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_synchronization.a(mutex.cc.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_synchronization.a(create_thread_identity.cc.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_synchronization.a(futex_waiter.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_kernel_timeout_internal.a(kernel_timeout.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_stacktrace.a(stacktrace.cc.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_malloc_internal.a(low_level_alloc.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_debugging_internal.a(address_is_readable.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time.a(clock.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time.a(duration.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time.a(time.cc.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_strings.a(ascii.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_strings.a(numbers.cc.o): relocation R_X86_64_32S against symbol `_ZN4absl14ascii_internal13kPropertyBitsE' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_strings.a(charconv.cc.o): relocation R_X86_64_32S against symbol `_ZN4absl16strings_internal10kFiveToNthE' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_strings.a(charconv_bigint.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_strings.a(charconv_parse.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_strings.a(memutil.cc.o): relocation R_X86_64_32S against symbol `_ZN4absl14ascii_internal8kToLowerE' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_strings.a(match.cc.o): relocation R_X86_64_32S against symbol `_ZN4absl14ascii_internal8kToUpperE' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_base.a(spinlock.cc.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_base.a(sysinfo.cc.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_base.a(thread_identity.cc.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_raw_logging_internal.a(raw_logging.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_int128.a(int128.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(time_zone_lookup.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(time_zone_fixed.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(time_zone_impl.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(time_zone_if.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(time_zone_info.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(time_zone_libc.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(time_zone_posix.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libabsl_time_zone.a(zone_info_source.cc.o): relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: lib/libre2.a(perl_groups.cc.o): warning: relocation in read-only section `.rodata'
      collect2: error: ld returned 1 exit status
      gmake[2]: *** [/tmp/pip-install-5pc6f7v2/qwen-cpp_bea53fb5d09446699f279818f534397f/build/lib.linux-x86_64-cpython-310/qwen_cpp/_C.cpython-310-x86_64-linux-gnu.so] Error 1
      gmake[1]: *** [CMakeFiles/_C.dir/all] Error 2
      gmake: *** [all] Error 2
      Traceback (most recent call last):
        File "/home/venus/anaconda3/envs/qwencpp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/venus/anaconda3/envs/qwencpp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/venus/anaconda3/envs/qwencpp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 117, in <module>
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9x95gl9o/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-9x95gl9o/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 112, in build_extension
        File "/home/venus/anaconda3/envs/qwencpp/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qwen-cpp
Failed to build qwen-cpp
ERROR: Could not build wheels for qwen-cpp, which is required to install pyproject.toml-based projects

**Comment by zzzcccxx** [comment]
一样，请问解决了吗

**Comment by Ka-ga** [comment]
<img width="645" alt="image" src="https://github.com/QwenLM/qwen.cpp/assets/107985257/ae87a553-7cbf-4205-a452-46abd00c89a5">

**Comment by web3aipro** [comment]
这个问题怎么解决？
