### ISSUE TITLE
convert failed

### ISSUE THREAD

**Issue by xwdreamer** [QwenLM/qwen.cpp#8]
```
% pip --version
pip 23.2.1 
% python3 --version
Python 3.9.16

% python qwen_cpp/convert.py -i /Volumes/data/huggingface/Qwen-14B-Chat  -t q4_0 -o qwen7b-ggml.bin
Traceback (most recent call last):
  File "/Volumes/data/huggingface/qwen.cpp/qwen_cpp/convert.py", line 262, in <module>
    main()
  File "/Volumes/data/huggingface/qwen.cpp/qwen_cpp/convert.py", line 256, in main
    convert(f, args.model_name_or_path, dtype=args.type)
  File "/Volumes/data/huggingface/qwen.cpp/qwen_cpp/convert.py", line 228, in convert
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True)
  File "/Users/xuwei/opt/anaconda3/envs/pytorch_m1/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 503, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/Users/xuwei/opt/anaconda3/envs/pytorch_m1/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/Users/xuwei/opt/anaconda3/envs/pytorch_m1/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/Users/xuwei/opt/anaconda3/envs/pytorch_m1/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: kernels. Run `pip install kernels`


 % pip3 install kernels
ERROR: Could not find a version that satisfies the requirement kernels (from versions: none)
ERROR: No matching distribution found for kernels
```

**Comment by xwdreamer** [comment]
测试了mac os和windows 11，都是报同样的错误：ImportError: This modeling file requires the following packages that were not found in your environment: kernels. Run `pip install kernels`

但是安装pip install kernels又报错。
