### ISSUE TITLE
转换为 bin时候报错 

### ISSUE THREAD

**Issue by anan1213095357** [QwenLM/qwen.cpp#80]
root@a:~/qwen/qwen.cpp# python3 qwen_cpp/convert.py -i /root/qwen/Qwen-1_8B-Chat -t q4_0 -o qwen1_8b.bin
Loading checkpoint shards:   0%|                                                                                    | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/qwen/qwen.cpp/qwen_cpp/convert.py", line 262, in <module>
    main()
  File "/root/qwen/qwen.cpp/qwen_cpp/convert.py", line 256, in main
    convert(f, args.model_name_or_path, dtype=args.type)
  File "/root/qwen/qwen.cpp/qwen_cpp/convert.py", line 228, in convert
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3903, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 505, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by dwojcik92** [comment]
Similar  issue here:

```
python3 qwen.cpp/qwen_cpp/convert.py -i Qwen1.5-MoE-A2.7B-Chat   -o Qwen1.5-MoE-A2.7B-Chat.gguf   -t q4_0
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 8/8 [00:14<00:00,  1.79s/it]
Traceback (most recent call last):
  File "/home/dwojcik/HF-to-GGUF_converter/qwen.cpp/qwen_cpp/convert.py", line 262, in <module>
    main()
  File "/home/dwojcik/HF-to-GGUF_converter/qwen.cpp/qwen_cpp/convert.py", line 256, in main
    convert(f, args.model_name_or_path, dtype=args.type)
  File "/home/dwojcik/HF-to-GGUF_converter/qwen.cpp/qwen_cpp/convert.py", line 230, in convert
    QwenConverter.convert(f, model, tokenizer, ggml_type)
  File "/home/dwojcik/HF-to-GGUF_converter/qwen.cpp/qwen_cpp/convert.py", line 182, in convert
    cls.dump_config(f, model.config, model.generation_config, tokenizer, ggml_type)
  File "/home/dwojcik/HF-to-GGUF_converter/qwen.cpp/qwen_cpp/convert.py", line 195, in dump_config
    config.seq_length,
  File "/home/dwojcik/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 263, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'Qwen2MoeConfig' object has no attribute 'seq_length'. Did you mean: 'max_length'?
```

**Comment by zhangfan-algo** [comment]
我也遇到了 貌似不太支持 求解
